application/models.py
from application import db, login_manager
from flask_login import UserMixin
from datetime import datetime

class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.String(1000), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    comment = db.Column(db.String(100), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False) 

    def __repr__(self):
        return ''.join([
            'User ID: ', self.user_id, '\r\n',
            'Title: ', self.title, '\r\n', self.content
            ])

@login_manager.user_loader
def load_user(id):
    return Users.query.get(int(id))


class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(30), nullable=False)
    last_name = db.Column(db.String(30), nullable=False)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    posts = db.relationship('Posts', backref='author', lazy=True)
    def __repr__(self):
        return ''.join([
		'UserID: ', str(self.id), '\r\n',
		'Email: ', self.email, '\r\n',
		'Name: ', self.first_name, ' ', self.last_name
	])

class AnsweredQuestion(db.Model):
   id = db.Column(db.Integer, primary_key=True)
   user_test_id = db.Column(db.Integer, db.ForeignKey('user_test.id'))
   question = db.Column(db.String(1000), nullable=False)
   answer = db.Column(db.String(1000), nullable=False)
   attempts = db.Column(db.Integer)
   completed = db.Column(db.Boolean, unique=False, default=False)

class UserTest(db.Model):
   id = db.Column(db.Integer, primary_key=True)
   answered_questions = db.relationship('AnsweredQuestion', backref='answered_question', lazy=False)

class Question(db.Model):
   id = db.Column(db.Integer, primary_key=True)
   test_id = db.Column(db.Integer, db.ForeignKey('test.id'))
   question = db.Column(db.String(1000), nullable=False)
   answer = db.Column(db.String(1000), nullable=False)

class Test(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    questions = db.relationship('Question', backref='test_question', lazy=False)

application/templates/about.html
{% extends "layout.html" %}
{% block body_content %}
    <p1> This page describes what my website is about?  </p1>
{% endblock %}

application/templates/account.html
{% extends "layout.html" %}
{% block body_content %}
        <h1> Account Name: {{current_user.first_name}} {{current_user.last_name}}</h1>
        <p> Need an account? Sign up</p>
        <div class='form'>
                <form method='POST' action=''>
                        {{ form.hidden_tag() }}
                        <div class='form_group'>
                                {{ form.first_name.label }}
                                {{ form.first_name }}
                                        {% if form.first_name.errors %}
                                                <div class="error">
                                                        {% for error in form.first_name.errors %}
                                                                <span>{{ error }}</span>
                                                        {% endfor %}
                                                </div>
                                        {% endif %}
                        </div>
                        <br>
                        <div class='form_group'>
                                {{ form.last_name.label }}
                                {{ form.last_name }}
                                        {% if form.last_name.errors %}
                                                <div class="error">
                                                        {% for error in form.last_name.errors %}
                                                                <span>{{ error }}</span>
                                                        {% endfor %}
                                                </div>
                                        {% endif %}
                        </div>
                        <br>
                        <div class='form_group'>
                                {{ form.email.label }}
                                {{ form.email }}
                                {% if form.email.errors %}
                                        <div class='error'>
                                                {% for error in form.email.errors %}
                                                        <span>{{ error }}</span>
                                                {% endfor %}
                                        </div>
                                {% endif %}
                        </div>
                        <br>
                        <div class='form_group'>
                                {{ form.submit }}
                        </div>
			<br>
			<form action="{{ url_for('account_delete') }}">
				<button type="submit">Delete your account</button>
			</form>
				
                </form>
        </div>
{% endblock %}

application/templates/analysis.html
{% extends "layout.html" %}
{% block body_content %}
	<p1> Analysis of test performance  </p1>
		<div class='form'>
			<form method='POST' action=''>

{% for result in results %}
	<div>					
                        <div class='form_group'>
				<h3> {{ result.title }} </h3>
				{{ result.question }}
				{{ result.answer }}
				{{ result.attempts }}
	</div>
	<br>
{% endfor %} 		



    <div class='form-group'>
        <form method='POST' action=''>
            {{ form.hidden_tag() }}
            {{ form.title.label }}
            {{ form.title }}
                {% if form.title.errors %}
                        <div class="error">
                                {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                {% endif %}
            <br>
            {{ form.content.label }}
            {{ form.content }}
                 {% if form.content.errors %}
                        <div class="error">
                                {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                {% endif %}
            <br>

	         
            {{ form.comment.label }}
            {{ form.comment }}
                 {% if form.comment.errors %}
                        <div class="error">
                                {% for error in form.comment.errors %}
                                        <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                {% endif %}
		<br>

            {{ form.submit }}
        </form>
    </div>
{% endblock %}

application/templates/home.html
{% extends "layout.html" %}
{% block body_content %}
<h1>Home page </h1>
<p>Welcome to this web app!</p>     

    {% for post in posts %}
        <div>
            <h3>{{ post.title }}</h3>
            <span>by <i>{{ post.author.first_name }} {{ post.author.last_name }}</i></span>
            <span>on the <i>{{ post.date_posted }}</i></span>
            <p>{{ post.content }}</p>
	    <p>{{ post.comment }}</p>
        </div>
	<form action="{{ url_for('delete_post', id=post.id) }}">
        <button type="submit">Delete Post</button>
	</form>
	{% endfor %}
{% endblock body_content %}

application/templates/layout.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<title>{{ title }} - Page</title>
</head>
<body>
<div class="navbar">
<a href="{{ url_for('home') }}">Home</a>
<a href="{{ url_for('about') }}">About</a>
{%  if  current_user.is_authenticated: %}
<a href="{{ url_for('post') }}">Post</a>
<a href="{{ url_for('logout') }}">Logout</a>
<a href="{{ url_for('account') }}">Account</a>
<a href="{{ url_for('question_set') }}">Question Set</a>
{% else: %}
<a href="{{ url_for('login') }}">Login</a>
<a href="{{ url_for('register') }}">Register</a>
{% endif %}
</div>
{% block body_content %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

application/templates/login.html
{% extends "layout.html" %}
{% block body_content %}
    <p1> Login screen  </p1>
{{ form.remember.label }}
{{ form.remember }}
        <div class='form'>
                <form method='POST' action=''>
                        {{ form.hidden_tag() }}
                        <div class='form_group'>
                                {{ form.email.label }}
                                {{ form.email }}
                                {% if form.email.errors %}
                                        <div class='error'>
                                                {% for error in form.email.errors %}
                                                        <span>{{ error }}</span>
                                                {% endfor %}
                                        </div>
                                {% endif %}
                        </div>
                        <br>
                        <div class='form_group'>
                                {{ form.password.label }}
                                {{ form.password }}
                                {% if form.password.errors %}
                                        <div class='error'>
                                                {% for error in form.password.errors %}
                                                        <span>{{ error }}</span>
                                                {% endfor %}
                                        </div>
                                {% endif %}
                        </div>
                        <br>
                        <div class='form_group'>
                                {{ form.submit }}
                        </div>
                </form>
        </div>
{% endblock %}

application/templates/post.html
{% extends "layout.html" %}
{% block body_content %}
    <div class='form-group'>
        <form method='POST' action=''>
            {{ form.hidden_tag() }}
            {{ form.title.label }}
            {{ form.title }}
 		{% if form.title.errors %}
                        <div class="error">
                                {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                {% endif %}
            <br>
            {{ form.content.label }}
            {{ form.content }}
		 {% if form.content.errors %}
                        <div class="error">
                                {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                {% endfor %}
                        </div>
                {% endif %}
            <br>
            {{ form.submit }}
        </form>
    </div>
{% endblock %}

application/templates/questionbankupload.html
{% extends "layout.html" %}
{% block body_content %}
    <p1> Please upload a set of questions and answers in the form of a CSV File!</p1>
	<!--<div class='form>
                <form method='POST' action=''>
			{{ form.hidden_tag() }}
                        <div class='form_group'>
                                {{ form.submit }}
                        </div>
                </form>
        </div>-->
	<a href='{{url_for("user_test_create")}}'> Take Test</a>
{% endblock %}

application/templates/register.html
{% extends "layout.html" %}
{% block body_content %}
	<h1> Registration Page</h1>
	<p> Need an account? Sign up</p>
	<div class='form'>
		<form method='POST' action=''>
			{{ form.hidden_tag() }}
                        <div class='form_group'>
				{{ form.first_name.label }}
				{{ form.first_name }}
					{% if form.first_name.errors %}
						<div class="error">
							{% for error in form.first_name.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% endif %}
			</div>
			<br>
			<div class='form_group'>
				{{ form.last_name.label }}
				{{ form.last_name }}
					{% if form.last_name.errors %}
						<div class="error">
							{% for error in form.last_name.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% endif %}
			</div>	
			<br>
			<div class='form_group'>
				{{ form.email.label }}
				{{ form.email }}
				{% if form.email.errors %}
					<div class='error'>
						{% for error in form.email.errors %}
							<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
			<br>
			<div class='form_group'>
                                {{ form.password.label }}
                                {{ form.password }}
                                {% if form.password.errors %}
                                        <div class='error'>
                                                {% for error in form.password.errors %}
                                                        <span>{{ error }}</span>
                                                {% endfor %}
                                        </div>
                                {% endif %}
                        </div>
			<br>
			<div class='form_group'>
                                {{ form.confirm_password.label }}
                                {{ form.confirm_password }}
                                {% if form.confirm_password.errors %}
                                        <div class='error'>
                                                {% for error in form.confirm_password.errors %}
                                                        <span>{{ error }}</span>
                                                {% endfor %}
                                        </div>
                                {% endif %}
                        </div>
			<br>
			<div class='form_group'>
				{{ form.submit }}
			</div>
		</form>
	</div>
{% endblock %}

application/templates/testpage.html
{% extends "layout.html" %}
{% block body_content %}
    <p1> Please take the your test!  </p1>
        <div class='form'>
            <form method='POST' action="{{ url_for('user_question', test_id=test_id, question_id=question.id)  }}" >
                        {{ form.hidden_tag() }}
                        <div class='form_group'>
                            {{ form.question.label }}: {{ question.question }} 
                            <br/>
                                {{ form.question }}
                                {% if form.question.errors %}
                                        <div class='error'>
						{% for error in form.question.errors %}
							<span>No questions left</span>
						{% endfor %}
                                        </div>
                                {% endif %}
			</div>
			<br>
			<div class='form_group'>
				{{ form.submit }}
			</div>
                </form>
        </div>
{% endblock %}